# Generated by Django 3.2 on 2025-06-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_title_description'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['review', 'author'], name='reviews_com_review__3f0c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['title', 'author'], name='reviews_rev_title_i_cc3b92_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['category'], name='reviews_tit_categor_462c42_idx'),
        ),
    ]
